Main/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mine/',include('first_app.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

first_app/urls.py
from django.urls import path
from . import views

app_name= "app"
urlpatterns = [
    path('blog',views.first_page,name='home'),
    path('blog/<slug:slug>',views.detail , name="detail")
]

first_app/models.py
from django.db import models
from django.utils.text import slugify
from django.utils import timezone

# Create your models here.
class Article(models.Model):
    Drafted = 'd'
    Published = 'p'
    STATUS_CHOICES = [
        ( Drafted,'در انتظار'),
        (Published , 'منتشر شده')
    ]
    title = models.CharField(max_length=200,verbose_name="عنوان مقاله")
    slug = models.SlugField(max_length = 200, unique=True,verbose_name="آدرس")
    description = models.TextField(verbose_name="محتوا")
    thumbnail = models.ImageField(upload_to="pics")
    published_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(auto_now=False)
    created_at = models.DateTimeField(auto_now_add=True)
    status = models.CharField(choices=STATUS_CHOICES,max_length=1,default='d',verbose_name="وضعیت")
    category = models.ManyToManyField('Category',verbose_name="دسته بندی")
    class Meta:
        verbose_name = "مقاله"
        verbose_name_plural = "مقاله" 

    def save(self, *args ,**kwargs):
        self.slug = slugify(self.title)
        return super().save(*args, **kwargs)   
    
    def __str__(self):
        return self.title
    
class Category(models.Model):
    title = models.CharField(max_length=256,verbose_name="عنوان")
    slug =models.SlugField(unique=True,verbose_name="آدرس")
    status = models.BooleanField(default=False,verbose_name = "آیا تایید شده هست؟")
    position = models.IntegerField(verbose_name="جایگاه")
    class Meta:
        verbose_name = "دسته بندی"
        verbose_name_plural =" دسته بندی ها"
        ordering = ['position']
        
    def __str__(self):
        return self.title

first_app/views.py
from django.shortcuts import render , HttpResponse
from .models import Article
# Create your views here.


def first_page(request):
    Article_data = Article.objects.filter(status='p').order_by('created_at')[:4]
    return render(request,'first_app/first_page.html',
                  {'article': Article_data}
                  )
    
def detail(request,slug):
    Article_data = Article.objects.filter(slug=slug)
    return render(request,'first_app/detail.html',{
        "article" : Article_data
    })

first_app/templates/first_app/detail.html
{% extends 'core.html' %}

{% load static %}

{% block stylesheet %}
    <link rel="stylesheet" type="text/css" href="{% static '' %}?version={{css_version}}">
{% endblock stylesheet%}

{% block body %}
    {%for articles in article%}
        {%include "first_app/first_page.html" %}
    {%endfor%}
{% endblock body %}

{% block scripts %}
    <script src="{% static ''%}?version={{ js_version }}" type="module"></script>
{% endblock scripts %}

first_app/templates/first_app/first_page.html
{%extends 'core.html' %}
{% load static %}

{% block stylesheet %}
    <link rel="stylesheet" type="text/css" href="{% static '' %}?version={{css_version}}">
{% endblock stylesheet%}

{% block body %}

    <h4><a href ="{% url "app:home" %}">Home-Page</a></h4>

    
    {% for articles in article%}
        <img src= "{{articles.thumbnail.url}}" alt="{{articles.title}}" wide="500" height="500"/>
        <h1> <a  href=" {%url 'app:detail' articles.slug %}">{{articles.title}}</a> </h1>
        <h3>{{articles.published_at}}</h3>
        <h2>{{articles.description}}</h2>
    {%endfor%}


{% endblock body %}

{% block scripts %}
    <script src="{% static '' %}?version={{ js_version }}" type="module"></script>
{% endblock scripts %}

templates/core.html
{% load static %}

{% block stylesheet %}
    <link rel="stylesheet" type="text/css" href="{% static '' %}?version={{css_version}}">
{% endblock stylesheet%}

{% block body %}
{% endblock body %}

{% block scripts %}
    <script src="{% static ''%}?version={{ js_version }}" type="module"></script>
{% endblock scripts %}